version: '3.8'
services: 
  node-webpack:
    container_name: node-webpack
    restart: always 
    build: 
      context: .
      dockerfile: ./images/Dockerfile
    volumes: 
      - /app/node_modules
      - ./www:/app 
    ports: 
      - "3000:3000"
